name: Build and Add release

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Upload artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv dist openapi-variable-provider-plugin
          zip -r openapi-variable-provider-plugin.zip openapi-variable-provider-plugin
          gh release upload ${{github.event.release.tag_name}} openapi-variable-provider-plugin.zip
